name = "tech-chat"
main = "index.js"
compatibility_date = "2026-06-18"

[[kv_namespaces]]
binding = "CHAT_DATA"
id = "213af5e001694a3ca1f75291ac87c09d"

[[durable_objects.bindings]]
name = "CHAT_ROOM"
class_name = "ChatRoom"

[[migrations]]
tag = "v1"
new_classes = ["ChatRoom"]

[vars]
